#!/bin/bash

#进入脚本所在目录，然后返回项目根目录
#scriptPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
scriptPath="/var/jenkins_home/jobs/EurekaServer/workspace/j-eureka/build-jenkins/"
cd $scriptPath
cd ../

echo "脚本所在目录:${scriptPath}"

#Docker容器基本信息
appHome="/var/jenkins_home/jobs/EurekaServer/workspace/j-eureka/target"
dockerName="j-eureka-2.7.4"
dockerPort="8088"
dockerJarVolumn="${appHome}/${dockerName }"

#将Jar 包复制到目录下
outputPath="${scriptPath}/${dockerName}";
if exist ${outputPath(
  rm -rf ${outputPath}
)
mkdir ${outputPath} && mkdir ${outputPath}/jar
cp ./target/*.jar ${outputPath}/jar/app.jar
# 将整个目录复制到应用目录中
cd ${scriptPath}
cp -rf ${outputPath} ${appHome}/
#停止删除现有容器
echo "停止删除容器:${dockerName}"
docker stop ${dockerName}&& docker rm ${dockerName}
#Docker容器运行命令
echo "运行容器"
docker run --name=j-eureka-2.7.4 -d -p 8088:8088 -v --network my-network /var/jenkins_home/jobs/EurekaServer/workspace/j-eureka/target/j-eureka-2.7.4.jar:/jar microserv/openjdk:1.0.0

exit 0