server:
  port: 8686

spring:
  application:
    name: stream-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    connect-timeout: 60
  cloud:
    stream:
      bindings:
        output:
          destination: usertopic
          content-type: application/json
      binder:
        brokers: 0.0.0.0:9092
        zk-nodes: 0.0.0.0:2181

eureka:
  client:
    service-url:
      defaultZone: http://lsc:123456@127.0.0.1:8088/eureka
    instance:
      instance-id: stream-server
logging:
  level:
    root: INFO