server:
  port: 8585

spring:
  redis:
    host: myredis
    port: 6379
    password:
    database: 0
    connect-timeout: 60
  profiles:
    active: dev
  application:
    name: provider-user
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          zk-nodes: zookeeper:2181
        bindings:
          input:
            destination: usertopic
            content-type: application/json
            group: productGroup
          #inboundUserMsg:
          #  destination: usertopic
          #  content-type: application/json
          #  group: productGroup

#  cloud:
#    config:
#      #profile: dev
#      name: application
#      uri: http://configserver

eureka:
  client:
    service-url:
      defaultZone: http://lsc:123456@euerekadocker:8088/eureka
  instance:
    instance-id: j-provider1
logging:
  level:
    root: INFO

# 配合spring-boot-starter-actuator，显示服务信息
management:
  endpoint:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"