spring:
  security:
    basic:
      enabled: true
    user:
      name: lsc
      password: 123456
server:
  port: 8088
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: ${EUREKA_URL}
      defaultZone: http://lsc:123456@localhost:8088/eureka