server:
  port: 8082
  servlet:
    context-path:
spring:
  application:
    name: j-consumer


eureka:
  client:
    service-url:
      defaultZone: http://lsc:123456@localhost:8088/eureka
    instance:
      instance-id: j-consumer
logging:
  level:
    root: INFO