server:
  port: 8033
spring:
  application:
    name: j-hystrix

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://lsc:123456@localhost:8088/eureka
  instance:
    instance-id: j-hystrix #修改Eureka上的默认描述信息

